LDFLAGS = -framework GLUT -framework OpenGL -lpng
offscreen: offscreen.cpp
	c++ $(LDFLAGS) -o offscreen offscreen.cpp
solar-system: solar-system.cpp
	c++ $(LDFLAGS) -o solar-system solar-system.cpp 

